version: '3'
services:
  client:
    image: tej7k/frontend:latest
    ports:
      - "3000:3000"

  server:
    image: tej7k/backend:latest
    ports:
      - "5000:5000" 
    environment:
      - ATLAS_URI="mongodb+srv://Jais07k:Jais@mongo07k@employees.kel2i.mongodb.net/?retryWrites=true&w=majority&appName=employees"
