name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Client Image
        run: |
          docker build -t tej7k/frontend .
          docker push tej7k/frontend:latest 

      - name: Build and Push Server Image
        run: |
          docker build -t tej7k/backend
          docker push tej7k/backend:latest

  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    steps:
      - name: SSH to EC2
        run: |
          docker pull tej7k/frontend:latest
          docker pull tej7k/backend:latest
          docker-compose -f docker-compose.prod.yml up -d
